# workflow name
name: Home Page CI

# master branch on push, auto run
on:
  push:
    branches:
      - master
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: 1. 检查master分支
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: 2. 设置Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3. 缓存
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}

      - name: 4. 安装插件
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export TZ='Asia/Shanghai'
          yarn install

      - name: 5. 生成页面并压缩
        run: |
          yarn run build

      - name: 6. 下载博客的rss订阅
        if: env.BLOG_RSS
        run: |
          wget -p dist ${{ secrets.BLOG_RSS }}
        env:
          BLOG_RSS: ${{secrets.BLOG_RSS}}

      - name: 7. 部署页面
        run: |
          cd ./dist
          ls
          git init
          git config --global user.name '${{ secrets.GIT_USER }}' 
          git config --global user.email '${{ secrets.GIT_MAIL }}'
          git add .
          git commit -m "Update"
          git push --force --all https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REPO }}

      - name: 8. 触发webhook
        run: |
          # 刷新相关资源
          curl https://purge.jsdelivr.net/gh/iServes/xiaokang.me/css/style.css
          curl https://purge.jsdelivr.net/gh/iServes/xiaokang.me/css/link.css
          curl https://purge.jsdelivr.net/gh/iServes/xiaokang.me/css/speaker.css
          curl https://purge.jsdelivr.net/gh/iServes/xiaokang.me/css/terminal.css
          curl https://purge.jsdelivr.net/gh/iServes/xiaokang.me/js/about.js
          curl https://purge.jsdelivr.net/gh/iServes/xiaokang.me/js/console.js
          curl https://purge.jsdelivr.net/gh/iServes/xiaokang.me/js/Speak.js
